# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DigiCardApp' do
  pod 'Firebase/Core'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DigiCardApp
  target 'DigiCardApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DigiCardAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DigiCardApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DigiCardApp-tvOS

end
